algoritmo "semnome"
// Função : 41) Desenvolva um programa que mostre na tela a
//seguinte contagem:
//100 95 90 85 80 ... 0 Acabou
// Autor :
// Data : 18/12/2023
// Seção de Declarações
var
     contador : inteiro
inicio
// Seção de Comandos
     contador <- 100
     enquanto (contador >= 0) faca
              escreva(contador)
              contador <- contador-5
     fimEnquanto
       escreva(" Acabou!!!!")
fimalgoritmo
