algoritmo "semnome"
// Função : 38) Escreva um programa que mostre na tela a
//seguinte contagem:
//6 7 8 9 10 11 Acabou!
// Autor :
// Data : 18/12/2023
// Seção de Declarações 
var
        contador : inteiro
inicio
// Seção de Comandos 
  contador <- 6
  
  enquanto (contador <= 11) faca
        escreva(contador)
        contador <- contador+1
  fimEnquanto
        escreva(" Acabou!")
fimalgoritmo
