algoritmo "semnome"
// Função :39) Faça um algoritmo que mostre na tela a seguinte contagem:
//10 9 8 7 6 5 4 3 Acabou!
// Autor :
// Data : 18/12/2023
// Seção de Declarações 
var
     contador : inteiro
inicio
// Seção de Comandos 
     contador <- 10
     enquanto (contador >= 3) faca
         escreva(contador)
         contador <- contador-1
     fimEnquanto
         escreva(" Acabou!!!!")
fimalgoritmo
