algoritmo "semnome"
// Função :  40) Crie um aplicativo que mostre na
//tela a seguinte contagem:
//0 3 6 9 12 15 18 Acabou!
// Autor :
// Data : 18/12/2023
// Seção de Declarações 
var
    contador : inteiro
inicio
// Seção de Comandos 
    contador <- 0
    enquanto (contador <= 18) faca
        escreva(contador)
        contador <- contador+3
    fimEnquanto
        escreva(" Acabou!!!!")
fimalgoritmo
