algoritmo "semnome"
// Função :    2) Faça um programa que leia o nome de uma pessoa e mostre uma mensagem de boasvindas para ela:
//Ex:
//Qual é o seu nome? João da Silva
//Olá João da Silva, é um prazer te conhecer!
// Autor :
// Data : 21/04/2023
// Seção de Declarações 
var
    nome : caractere
inicio
// Seção de Comandos 
  escreval("*****Exercicio 2******")
  escreva("Informe o seu nome: ")
  leia(nome)
  escreva("Olá ",nome,",é um prazer ti conhecer!!!")
  
fimalgoritmo
