algoritmo "semnome"
// Função :
// Autor :
// Data : 03/05/2023
// Seção de Declarações
//20) Desenvolva um programa que leia um número inteiro e mostre se ele é PAR ou
//ÍMPAR.
var
      n : inteiro
inicio
// Seção de Comandos
    escreval(" *******Exercicio 20******")
    escreva("Informe um número: ")
    leia(n)
    se (n%2 = 0) entao
     escreval("Esse número informado é PAR!!!!")
    senao
       escreval("O número informado é IMPAR!!!!")
    fimse
fimalgoritmo
